version: "3"
services:
  tad:
    image: postgres:9.5
    container_name: "postgres"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - TZ=GMT
    restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
